import {combineReducers} from 'redux'
import {routerReducer} from 'react-router-redux'
import {
    AUTH_INFO,
    EMP_INFO,
    IS_OPEN_MAIN_MENU,
    IS_DRAG_EVENT_CALENDAR,
    ORGANIZATION_TEAM,
    MASTER_EMPLOYEE_DATA,
    MASTER_ALL,

    CALENDAR_MASTER_EVENTS_DATA,
    CALENDAR_MASTER_BRANCH_LOCATION_DATA,
    CALENDAR_MASTER_MARKET_LOCATION_DATA,
    DOCUMENT_MASTER_CATEGORY,
    DOCUMENT_FOLDER_N_FILES
} from './master'

import {CALENDAR_EVENT_DATA, CALENDAR_EVENT_NON_CONFIRM, IS_LOAD_CALENDAR_EVENT} from './calendar'

import { 
    DOCUMENTSCAN_GET_BAISCINFO,
    DOCUMENTSCAN_DASHBOARD,
    DOCUMENTSCAN_MISSINGDOC,
    DOCUMENTSCAN_RETURNCODE,
    // DOCUMENTSCAN_GRID_MESSAGE,
    // DOCUMENTSCAN_CREATE_RETURNCODE,
    // DOCUMENTSCAN_CREATE_MESSAGE,
    DOCUMENTSCAN_RETURNCODE_VERIFY,
    LOAD_MASTER_RETURNREASON,
    LOAD_RETURNCODE_BUNDLE,   
    LOAD_MASTER_RETURNSTATUS,
    CREATE_RETURNCODE_BUNDLE,
    DOCUMENTSCAN_GET_BORROWER

} from './document'

import { 
    PCIS_MASTER_REGION, 
    PCIS_MASTER_AREA, 
    PCIS_MASTER_TEAM,
    PCIS_MASTER_EMPLOYEE,

    PCISCRM_MASTER_RESPONSE,
    PCISCRM_MASTER_ACTION,

    PCISCRM_LEADTOPUP_HEADER,
    PCISCRM_LOT_LEADTOPUP_DASHBOARD,
    PCISCRM_LEADTOPUP_DASHBOARD,
    PCISCRM_LEADTOPUP_SUMMARY,
    
    PCISCRM_LEADTOPUP_LOAD_ACTIONNOTE,
    PCISCRM_LEADTOPUP_CREATE_ACTIONNOTE,

    // REFER LEAD
    PCISCRM_USER_AUTHEN_PROFILE,
    PCISCRM_LEADCHANNEL_DASHBOARD,
    PCISCRM_LEADCHANNEL_DASHBOARD_SUMMARY,
    PCISCRM_LEADCHANNEL_DASHBOARD_SUMMARY_SUB,
    PCISCRM_LEADCHANNEL_PRODUCT_TRANSFER,
    PCISCRM_REFER_LEADCHANNEL_LOAD_ACTIONNOTE,
    PCISCRM_REFER_LEADCHANNEL_CREATE_ACTIONNOTE,
    PCISCRM_REFER_LEADCHANNEL_UPDATE_CUSTPROFILE,
    PCISCRM_REFER_LEADCHANNEL_HISTORY_CUSTPROFILE,

    PCISCRM_MASTER_LEADCHANNEL_RANK_SCORE, 
    PCISCRM_MASTER_LEADCHANNEL_SOURCE_CHANNEL,
    PCISCRM_MASTER_LEADCHANNEL_SUBSOURCE_CHANNEL,
    PCISCRM_MASTER_PRODUCT_GROUP,

    PCISCRM_FIND_BRANCH_IN_CUSTAREA,
    PCISCRM_FIND_EMPLOYEE_IN_CUSTAREA,
    PCISCRM_LEADCHANNEL_ASSIGNMENT_APPL_NEWOWNER,

    //  NEW LEAD TOP UP
    PCISCRM_NEWLEAD_TOPUP_DASHBOARD,
    PCISCRM_NEWLEAD_TOPUP_DASHBOARD_SUMMARY,
    PCISCRM_NEWLEAD_TOPUP_DASHBOARD_SUBSUMMARY,
    PCISCRM_CREATE_PROHIBITE_CUSTOMER,
    PCISCRM_MASTER_LOT_LIST

} from './pcis'

export default combineReducers({
    routing: routerReducer,

    AUTH_INFO,
    EMP_INFO,
    IS_OPEN_MAIN_MENU,
    IS_DRAG_EVENT_CALENDAR,

    MASTER_ALL,

    ORGANIZATION_TEAM,
    MASTER_EMPLOYEE_DATA,

    CALENDAR_MASTER_EVENTS_DATA,
    CALENDAR_EVENT_NON_CONFIRM,
    CALENDAR_MASTER_BRANCH_LOCATION_DATA,
    CALENDAR_MASTER_MARKET_LOCATION_DATA,

    CALENDAR_EVENT_DATA,
    CALENDAR_EVENT_NON_CONFIRM,
    IS_LOAD_CALENDAR_EVENT,

    DOCUMENTSCAN_GET_BAISCINFO,
    DOCUMENTSCAN_GET_BORROWER,
    DOCUMENTSCAN_DASHBOARD,
    DOCUMENTSCAN_MISSINGDOC,
    DOCUMENTSCAN_RETURNCODE,
    // DOCUMENTSCAN_GRID_MESSAGE,
    // DOCUMENTSCAN_CREATE_RETURNCODE,
    // DOCUMENTSCAN_CREATE_MESSAGE,
    DOCUMENTSCAN_RETURNCODE_VERIFY,
    LOAD_RETURNCODE_BUNDLE,
    CREATE_RETURNCODE_BUNDLE,

    LOAD_MASTER_RETURNSTATUS,
    LOAD_MASTER_RETURNREASON,
    DOCUMENT_MASTER_CATEGORY,

    // PCIS
    PCIS_MASTER_REGION, 
    PCIS_MASTER_AREA, 
    PCIS_MASTER_TEAM,
    PCIS_MASTER_EMPLOYEE,
    
    PCISCRM_MASTER_RESPONSE,
    PCISCRM_MASTER_ACTION,
    DOCUMENT_FOLDER_N_FILES,

    // TOPUP
    PCISCRM_LEADTOPUP_HEADER,
    PCISCRM_LOT_LEADTOPUP_DASHBOARD,
    PCISCRM_LEADTOPUP_DASHBOARD,
    PCISCRM_LEADTOPUP_SUMMARY,
    
    PCISCRM_LEADTOPUP_LOAD_ACTIONNOTE,
    PCISCRM_LEADTOPUP_CREATE_ACTIONNOTE,

    // NEW LEAD TOP UP
    PCISCRM_NEWLEAD_TOPUP_DASHBOARD,
    PCISCRM_NEWLEAD_TOPUP_DASHBOARD_SUMMARY,
    PCISCRM_NEWLEAD_TOPUP_DASHBOARD_SUBSUMMARY,
    PCISCRM_CREATE_PROHIBITE_CUSTOMER,
    PCISCRM_MASTER_LOT_LIST,
    PCISCRM_MASTER_PRODUCT_GROUP,

    // REFER LEAD
    PCISCRM_USER_AUTHEN_PROFILE,
    
    PCISCRM_LEADCHANNEL_DASHBOARD,
    PCISCRM_LEADCHANNEL_DASHBOARD_SUMMARY,
    PCISCRM_LEADCHANNEL_DASHBOARD_SUMMARY_SUB,
    PCISCRM_LEADCHANNEL_PRODUCT_TRANSFER,
    PCISCRM_REFER_LEADCHANNEL_LOAD_ACTIONNOTE,
    PCISCRM_REFER_LEADCHANNEL_CREATE_ACTIONNOTE,
    PCISCRM_REFER_LEADCHANNEL_UPDATE_CUSTPROFILE,
    PCISCRM_REFER_LEADCHANNEL_HISTORY_CUSTPROFILE,
    
    PCISCRM_MASTER_LEADCHANNEL_RANK_SCORE, 
    PCISCRM_MASTER_LEADCHANNEL_SOURCE_CHANNEL,
    PCISCRM_MASTER_LEADCHANNEL_SUBSOURCE_CHANNEL,

    PCISCRM_FIND_BRANCH_IN_CUSTAREA,
    PCISCRM_FIND_EMPLOYEE_IN_CUSTAREA,
    PCISCRM_LEADCHANNEL_ASSIGNMENT_APPL_NEWOWNER
})
