export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const SET_AUTHENTICATION_REQUEST = 'SET_AUTHENTICATION_REQUEST'
export const SET_EMPLOYEE_INFO_REQUEST = 'SET_EMPLOYEE_INFO_REQUEST'
export const ON_OPEN_MAIN_MENU = 'ON_OPEN_MAIN_MENU'
export const ON_DRAG_EVENT_CALENDAR = 'ON_DRAG_EVENT_CALENDAR'

export const LOAD_MASTER_ORGANIZATION_TEAM_REQUEST = 'LOAD_MASTER_ORGANIZATION_TEAM_REQUEST'
export const LOAD_MASTER_ORGANIZATION_TEAM_SUCCESS = 'LOAD_MASTER_ORGANIZATION_TEAM_SUCCESS'
export const LOAD_MASTER_ORGANIZATION_TEAM_FAILED = 'LOAD_MASTER_ORGANIZATION_TEAM_FAILED'

export const LOAD_MASTER_EMPLOYEE_REQUEST = 'LOAD_MASTER_EMPLOYEE_REQUEST'
export const LOAD_MASTER_EMPLOYEE_SUCCESS = 'LOAD_MASTER_EMPLOYEE_SUCCESS'
export const LOAD_MASTER_EMPLOYEE_FAILED = 'LOAD_MASTER_EMPLOYEE_FAILED'

export const LOAD_CALENDAR_MASTER_EVENTS_REQUEST = 'LOAD_CALENDAR_MASTER_EVENTS_REQUEST'
export const LOAD_CALENDAR_MASTER_EVENTS_SUCCESS = 'LOAD_CALENDAR_MASTER_EVENTS_SUCCESS'
export const LOAD_CALENDAR_MASTER_EVENTS_FAILED = 'LOAD_CALENDAR_MASTER_EVENTS_FAILED'

export const LOAD_CALENDAR_MASTER_BRANCH_LOCATION_REQUEST = 'LOAD_CALENDAR_MASTER_BRANCH_LOCATION_REQUEST'
export const LOAD_CALENDAR_MASTER_BRANCH_LOCATION_SUCCESS = 'LOAD_CALENDAR_MASTER_BRANCH_LOCATION_SUCCESS'
export const LOAD_CALENDAR_MASTER_BRANCH_LOCATION_FAILED = 'LOAD_CALENDAR_MASTER_BRANCH_LOCATION_FAILED'

export const LOAD_CALENDAR_MASTER_MARKET_LOCATION_REQUEST = 'LOAD_CALENDAR_MASTER_MARKET_LOCATION_REQUEST'
export const LOAD_CALENDAR_MASTER_MARKET_LOCATION_SUCCESS = 'LOAD_CALENDAR_MASTER_MARKET_LOCATION_SUCCESS'
export const LOAD_CALENDAR_MASTER_MARKET_LOCATION_FAILED = 'LOAD_CALENDAR_MASTER_MARKET_LOCATION_FAILED'

export const LOAD_CALENDAR_EVENT_REQUEST = 'LOAD_CALENDAR_EVENT_REQUEST'
export const LOAD_CALENDAR_EVENT_SUCCESS = 'LOAD_CALENDAR_EVENT_SUCCESS'
export const LOAD_CALENDAR_EVENT_FAILED = 'LOAD_CALENDAR_EVENT_FAILED'

export const INSERT_CALENDAR_EVENT_REQUEST = 'INSERT_CALENDAR_EVENT_REQUEST'
export const INSERT_CALENDAR_EVENT_SUCCESS = 'INSERT_CALENDAR_EVENT_SUCCESS'
export const INSERT_CALENDAR_EVENT_FAILED = 'INSERT_CALENDAR_EVENT_FAILED'

export const UPDATE_CALENDAR_EVENT_REQUEST = 'UPDATE_CALENDAR_EVENT_REQUEST'
export const UPDATE_CALENDAR_EVENT_SUCCESS = 'UPDATE_CALENDAR_EVENT_SUCCESS'
export const UPDATE_CALENDAR_EVENT_FAILED = 'UPDATE_CALENDAR_EVENT_FAILED'

export const DELETE_CALENDAR_EVENT_REQUEST = 'DELETE_CALENDAR_EVENT_REQUEST'
export const DELETE_CALENDAR_EVENT_SUCCESS = 'DELETE_CALENDAR_EVENT_SUCCESS'
export const DELETE_CALENDAR_EVENT_FAILED = 'DELETE_CALENDAR_EVENT_FAILED'

export const LOAD_MASTER_REQUEST = 'LOAD_MASTER_REQUEST'
export const LOAD_MASTER_SUCCESS = 'LOAD_MASTER_SUCCESS'
export const LOAD_MASTER_FAILURE = 'LOAD_MASTER_FAILURE'


/** PROJECT DOCUMENT SCAN **/
export const LOAD_DOCUMENTSCAN_REQUEST = 'LOAD_DOCUMENTSCAN_REQUEST'
export const LOAD_DOCUMENTSCAN_SUCCESS = 'LOAD_DOCUMENTSCAN_SUCCESS'
export const LOAD_DOCUMENTSCAN_FAILURE = 'LOAD_DOCUMENTSCAN_FAILURE'

export const LOAD_MISSINGDOC_REQUEST = 'LOAD_MISSINGDOC_REQUEST'
export const LOAD_MISSINGDOC_SUCCESS = 'LOAD_MISSINGDOC_SUCCESS'
export const LOAD_MISSINGDOC_FAILURE = 'LOAD_MISSINGDOC_FAILURE'

export const LOAD_DOCUMENTSCAN_RETURNCODE_REQUEST = 'LOAD_DOCUMENTSCAN_RETURNCODE_REQUEST'
export const LOAD_DOCUMENTSCAN_RETURNCODE_SUCCESS = 'LOAD_DOCUMENTSCAN_RETURNCODE_SUCCESS'
export const LOAD_DOCUMENTSCAN_RETURNCODE_FAILURE = 'LOAD_DOCUMENTSCAN_RETURNCODE_FAILURE'

// export const LOAD_DOCUMENTSCAN_GRID_MESSAGE_REQUEST = 'LOAD_DOCUMENTSCAN_GRID_MESSAGE_REQUEST'
// export const LOAD_DOCUMENTSCAN_GRID_MESSAGE_SUCCESS = 'LOAD_DOCUMENTSCAN_GRID_MESSAGE_SUCCESS'
// export const LOAD_DOCUMENTSCAN_GRID_MESSAGE_FAILURE = 'LOAD_DOCUMENTSCAN_GRID_MESSAGE_FAILURE'

// export const LOAD_DOCUMENTSCAN_CREATE_RETURNCODE_REQUEST = 'LOAD_DOCUMENTSCAN_CREATE_RETURNCODE_REQUEST'
// export const LOAD_DOCUMENTSCAN_CREATE_RETURNCODE_SUCCESS = 'LOAD_DOCUMENTSCAN_CREATE_RETURNCODE_SUCCESS'
// export const LOAD_DOCUMENTSCAN_CREATE_RETURNCODE_FAILURE = 'LOAD_DOCUMENTSCAN_CREATE_RETURNCODE_FAILURE'

// export const LOAD_DOCUMENTSCAN_CREATE_MESSAGE_REQUEST = 'LOAD_DOCUMENTSCAN_CREATE_MESSAGE_REQUEST'
// export const LOAD_DOCUMENTSCAN_CREATE_MESSAGE_SUCCESS = 'LOAD_DOCUMENTSCAN_CREATE_MESSAGE_SUCCESS'
// export const LOAD_DOCUMENTSCAN_CREATE_MESSAGE_FAILURE = 'LOAD_DOCUMENTSCAN_CREATE_MESSAGE_FAILURE'

export const LOAD_BAISC_INFO_REQUEST = 'LOAD_BAISC_INFO_REQUEST'
export const LOAD_BAISC_INFO_SUCCESS = 'LOAD_BAISC_INFO_SUCCESS'
export const LOAD_BAISC_INFO_FAILURE = 'LOAD_BAISC_INFO_FAILURE'

export const LOAD_BORROWER_INFO_REQUEST = 'LOAD_BORROWER_INFO_REQUEST'
export const LOAD_BORROWER_INFO_SUCCESS = 'LOAD_BORROWER_INFO_SUCCESS'
export const LOAD_BORROWER_INFO_FAILURE = 'LOAD_BORROWER_INFO_FAILURE'

export const LOAD_MASTER_RETURNCODE_REQUEST = 'LOAD_MASTER_RETURNCODE_REQUEST'
export const LOAD_MASTER_RETURNCODE_SUCCESS = 'LOAD_MASTER_RETURNCODE_SUCCESS'
export const LOAD_MASTER_RETURNCODE_FAILURE = 'LOAD_MASTER_RETURNCODE_FAILURE'

export const LOAD_MASTER_RETURNREASON_REQUEST = 'LOAD_MASTER_RETURNREASON_REQUEST'
export const LOAD_MASTER_RETURNREASON_SUCCESS = 'LOAD_MASTER_RETURNREASON_SUCCESS'
export const LOAD_MASTER_RETURNREASON_FAILURE = 'LOAD_MASTER_RETURNREASON_FAILURE'

export const LOAD_MASTER_CATEGORY_REQUEST = 'LOAD_MASTER_CATEGORY_REQUEST'
export const LOAD_MASTER_CATEGORY_SUCCESS = 'LOAD_MASTER_CATEGORY_SUCCESS'
export const LOAD_MASTER_CATEGORY_FAILURE = 'LOAD_MASTER_CATEGORY_FAILURE'

export const LOAD_FOLDER_N_FILES_REQUEST = 'LOAD_FOLDER_N_FILES_REQUEST'
export const LOAD_FOLDER_N_FILES_SUCCESS = 'LOAD_FOLDER_N_FILES_SUCCESS'
export const LOAD_FOLDER_N_FILES_FAILURE = 'LOAD_FOLDER_N_FILES_FAILURE'

export const LOAD_MASTER_STATUSCODE_REQUEST = 'LOAD_MASTER_STATUSCODE_REQUEST'
export const LOAD_MASTER_STATUSCODE_SUCCESS = 'LOAD_MASTER_STATUSCODE_SUCCESS'
export const LOAD_MASTER_STATUSCODE_FAILURE = 'LOAD_MASTER_STATUSCODE_FAILURE'

export const DOCUMENTSCAN_LOAD_RETURNCODE_REQUEST = 'DOCUMENTSCAN_LOAD_RETURNCODE_REQUEST'
export const DOCUMENTSCAN_LOAD_RETURNCODE_SUCCESS = 'DOCUMENTSCAN_LOAD_RETURNCODE_SUCCESS'
export const DOCUMENTSCAN_LOAD_RETURNCODE_FAILURE = 'DOCUMENTSCAN_LOAD_RETURNCODE_FAILURE'

export const DOCUMENTSCAN_CREATE_RETURNCODE_REQUEST = 'DOCUMENTSCAN_CREATE_RETURNCODE_REQUEST'
export const DOCUMENTSCAN_CREATE_RETURNCODE_SUCCESS = 'DOCUMENTSCAN_CREATE_RETURNCODE_SUCCESS'
export const DOCUMENTSCAN_CREATE_RETURNCODE_FAILURE = 'DOCUMENTSCAN_CREATE_RETURNCODE_FAILURE'
